[project]
name = "kaggle-pacakge"
version = "0.1.0"
description = "Starter template for Kaggle and ML competitions."
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["kaggle>=1.7.4.5"]
